version: '3.4'
services:
  team-tools-server:
    build: ./packages/server
    environment:
      - CORS_ALLOW_ORIGIN=http://localhost:4173
    ports:
      - "3000:3000"

  team-tools-client:
    build:
      context: ./packages/client
      args:
        - VITE_APP_TITLE=Team Tools
        - VITE_APP_API_HOST=http://localhost:3000
        - VITE_APP_WEBSOCKET_HOST=ws://localhost:3000
        - VITE_APP_STORY_POINTING_OPTIONS=0,0.5,1,2,3,5,8,?
    ports:
      - "4173:4173"
